BCDice: ゲームシステム一覧・検索機能を追加する
cre-ne-jp/rgrb pull request #203
Opened 2021-05-02 12:37 UTC by ochaochaocha3

BCDiceを使用する際にゲームシステムIDを探しやすくするため、以下のコマンドを追加します。

* `.bcdice-systems`：[BCDice公式サイトの対応ゲームシステム一覧ページ](https://bcdice.org/systems/)のURLを出力します。
* `.bcdice-search-id`：IDを基準としてゲームシステムを検索します。
* `.bcdice-search-name`：名称を基準としてゲームシステムを検索します。キーワードを半角空白または全角空白区切りで複数指定することで、AND検索も可能です。

ゲームシステム検索機能については、各チャットシステムの特徴に合わせて一覧の出力形式を変化させてみました。IRCボットの場合は、1行でカンマ区切りの一覧を出力します。一方で、Discordボットの場合はMarkdownを使用して装飾付き、複数行で出力します。

# スクリーンショット

## `.bcdice-systems` ：

<img width="501" alt="bcdice-systems" src="https://user-images.githubusercontent.com/2551173/116813169-6a793980-ab8d-11eb-8154-5265b9b493a7.png">

## `.bcdice-search-{id,name}`

### IRCボット

<img width="1034" alt="bcdice-search-irc" src="https://user-images.githubusercontent.com/2551173/116813238-d6f43880-ab8d-11eb-9c0d-be81f0e79454.png">

### Discordボット

<img width="542" alt="bcdice-search" src="https://user-images.githubusercontent.com/2551173/116813268-fee39c00-ab8d-11eb-9eb0-9a433cf256bc.png">

Markdownで装飾しているため、Markdownの特殊文字はエスケープするようにしました。

<img width="426" alt="bcdice-search-escape" src="https://user-images.githubusercontent.com/2551173/116813302-1ae73d80-ab8e-11eb-8a35-3110c6554d50.png">

### ゲームシステム名でAND検索

<img width="582" alt="bcdice-search-name-filter" src="https://user-images.githubusercontent.com/2551173/116813375-75809980-ab8e-11eb-9cb4-4fa6746ed861.png">

2021-05-02 13:35 UTC, ochaochaocha3 commented
IRCログより、IRCボットの出力関連の会話。

```
22:28:28 <ocha> Discordボットだと、凡例を出さなくても一目瞭然だと思うのですが、IRCだと見分けにくいかなぁ
22:29:04 <DiscordIRC> <13koi-chan> IRCの文字装飾は使うつもりないんですよね？
22:30:40 <ocha> IRCでも文字装飾使えますね。この出力だとどうでしょう、IDを太字にするかな
22:31:15 <DiscordIRC> <13koi-chan> それがよさそうです＞ID太字
22:31:48 <ocha> よし、ID太字入れてみますね
22:32:02 <DiscordIRC> <13koi-chan> お願いしますー 
```

2021-05-02 16:12 UTC, ochaochaocha3 commented
a992a332a24e6506313af7fc54ea38379a0908f6 IRCメッセージをmIRC制御文字で装飾して見やすくしました。

<img width="1033" alt="bcdice-search-mirc_codes" src="https://user-images.githubusercontent.com/2551173/116819792-922bca00-abac-11eb-9156-bb2f50be6c7b.png">

2021-05-03 03:04 UTC, koi-chan requested changes
レビュー致しました。
ToDo を減らす機能の実装をして頂きありがとうございます！

2021-05-03 03:04 UTC, koi-chan commented on lib/rgrb/plugin/bcdice/generator.rb
> +        MIRC_RESET = "\x0F"
mIRC 制御文字の挿入は、[Formatting](https://www.rubydoc.info/github/cre-ne-jp/mcinch/master/Cinch/Formatting) を使用して頂けないでしょうか。

2021-05-03 04:29 UTC, ochaochaocha3 commented on lib/rgrb/plugin/bcdice/generator.rb
> +        MIRC_RESET = "\x0F"
単純な処理で大丈夫そうと思っていましたが、エスケープ等も考慮するとFormattingがいいですね。変えてみます。

2021-05-06 10:37 UTC, koi-chan approved these changes
ありがとうございます！
問題ないと思いますので、マージします。

2021-05-06 10:37 UTC, merged